name: Build Python Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - release*

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Test the build with the latest CUDA toolkit and several Python versions
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']

    name: "Python ${{ matrix.python }} / NVCC (CUDA 12.6.3) / ubuntu-latest"
    runs-on: ubuntu-latest
    # see https://hub.docker.com/r/nvidia/cuda
    container: nvidia/cuda:12.6.3-devel-ubuntu24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y lsb-release unzip git && apt-get clean all

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Upload binaries to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/ggnn-*-linux_x86_64.whl
        file_glob: true
        tag: ${{ github.ref }}
